  sudo: false

  language: java

# To compile with Maven using java as language
#  scala:
#   - 2.10.5

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk7
#  - openjdk8

# blocklist
  branches:
    except:

# safelist
  branches:
    only:
    - 1.0
    
  before_install:
  
  before_script:
  
  script:
    - mvn -e -fn -DskipTests=true install prepare-package

  notifications:
    email:
      - ns68751+tci@gmail.com
