  sudo: false

  language: java

# To compile with Maven using java as language
#  scala:
#   - 2.10.5

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

jdk:
  - oraclejdk7
#  - openjdk8

# blocklist
  branches:
    except:

# safelist
  branches:
    only:
    - 1.0
    
  before_install:
    - wget https://github.com/n10n/DockerNode/raw/master/m2scalaz210700.tar.gz -O $HOME/m2scalaz210700.tar.gz
    - tar -xzvf m2scalaz210700.tar.gz -C $HOME; rm -f $HOME/m2scalaz210700.tar.gz
#    - wget https://github.com/synereo/compilednode/raw/master/lib/specialK-1.1.8.5.jar -O $HOME/.m2/repository/com/biosimilarity/lift/specialK/1.1.8.5/specialK-1.1.8.5.jar
#    - wget https://github.com/synereo/compilednode/raw/master/lib/pom-specialk.xml -O $HOME/.m2/repository/com/biosimilarity/lift/specialK/1.1.8.5/specialK-1.1.8.5.pom
#    - wget https://github.com/synereo/compilednode/raw/master/lib/agentservices-store-ia-1.9.5.jar -O $HOME/.m2/repository/com/protegra-ati/agentservices-store-ia/1.9.5/agentservices-store-ia-1.9.5.jar
#    - wget https://github.com/synereo/compilednode/raw/master/lib/pom-agentservicestore.xml -O $HOME/.m2/repository/com/protegra-ati/agentservices-store-ia/1.9.5/agentservices-store-ia-1.9.5.pom
  
  before_script:
    - wget https://github.com/n10n/DockerNode/raw/master/m2scalaz210700.tar.gz -O $HOME/m2scalaz210700.tar.gz
    - tar -xzvf m2scalaz210700.tar.gz -C $HOME; rm -f $HOME/m2scalaz210700.tar.gz
#    - wget https://github.com/synereo/compilednode/raw/master/lib/specialK-1.1.8.5.jar -O $HOME/.m2/repository/com/biosimilarity/lift/specialK/1.1.8.5/specialK-1.1.8.5.jar
#    - wget https://github.com/synereo/compilednode/raw/master/lib/pom-specialk.xml -O $HOME/.m2/repository/com/biosimilarity/lift/specialK/1.1.8.5/specialK-1.1.8.5.pom
#    - wget https://github.com/synereo/compilednode/raw/master/lib/agentservices-store-ia-1.9.5.jar -O $HOME/.m2/repository/com/protegra-ati/agentservices-store-ia/1.9.5/agentservices-store-ia-1.9.5.jar
#    - wget https://github.com/synereo/compilednode/raw/master/lib/pom-agentservicestore.xml -O $HOME/.m2/repository/com/protegra-ati/agentservices-store-ia/1.9.5/agentservices-store-ia-1.9.5.pom
  
  script:
    - mvn -e -fn -DskipTests=true install prepare-package

  notifications:
    email:
      - ns68751+tci@gmail.com
